apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: MinIO
metadata:
  name: minio
  namespace: example-env
spec:
  clusterName: my-cluster
  namespace: minio
  labels:
    team: platform
    environment: production
  providerConfigRef:
    name: my-cluster
    kind: ProviderConfig
  helm:
    minio:
      values:
        mode: distributed
        replicas: 4
        persistence:
          enabled: true
          size: 50Gi
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
